
package com.ctfs.esockettransact;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "esocketTransact", targetNamespace = "http://ctfs.com/esocketTransact/", wsdlLocation = "WEB-INF/wsdl/esocketTransact.wsdl")
public class EsocketTransact_Service
    extends Service
{

    private final static URL ESOCKETTRANSACT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ctfs.esockettransact.EsocketTransact_Service.class.getName());

    static {
        URL url = null;
        try {
            url = com.ctfs.esockettransact.EsocketTransact_Service.class.getResource("/WEB-INF/wsdl/esocketTransact.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/esocketTransact.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/esocketTransact.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ESOCKETTRANSACT_WSDL_LOCATION = url;
    }

    public EsocketTransact_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsocketTransact_Service() {
        super(ESOCKETTRANSACT_WSDL_LOCATION, new QName("http://ctfs.com/esocketTransact/", "esocketTransact"));
    }

    /**
     * 
     * @return
     *     returns EsocketTransact
     */
    @WebEndpoint(name = "esocketTransactSOAP")
    public EsocketTransact getEsocketTransactSOAP() {
        return super.getPort(new QName("http://ctfs.com/esocketTransact/", "esocketTransactSOAP"), EsocketTransact.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EsocketTransact
     */
    @WebEndpoint(name = "esocketTransactSOAP")
    public EsocketTransact getEsocketTransactSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://ctfs.com/esocketTransact/", "esocketTransactSOAP"), EsocketTransact.class, features);
    }

}
