
package com.ctfs.esockettransact;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PGCError", targetNamespace = "http://ctfs.com/esocketTransactIo/")
public class PGCError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.ctfs.esockettransactio.PGCError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PGCError(String message, com.ctfs.esockettransactio.PGCError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PGCError(String message, com.ctfs.esockettransactio.PGCError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ctfs.esockettransactio.PGCError
     */
    public com.ctfs.esockettransactio.PGCError getFaultInfo() {
        return faultInfo;
    }

}
