
--Master table to store WICI related configurable parameters--
CREATE TABLE WEBIC_OWNER.WICI_WHITELIST 
(
    AUTHFIELD_VALUE VARCHAR2(200) NOT NULL,
    AUTHORIZED INTEGER,
    DATE_ADDED TIMESTAMP(6),
    DATE_UPDATED TIMESTAMP(6),
    CONSTRAINT WICI_WHITELIST_PK PRIMARY KEY (AUTHFIELD_VALUE)  
);

GRANT SELECT, INSERT, UPDATE, DELETE ON WICI_WHITELIST TO WEBIC_APP;

CREATE SYNONYM WEBIC_APP.WICI_WHITELIST FOR WEBIC_OWNER.WICI_WHITELIST;

 
--Trigger to automatically insert and update user name and time stamp on WEBIC_OWNER.WICI_WHITELIST--
CREATE OR REPLACE TRIGGER TRG_WICI_WHITELIST
BEFORE INSERT OR UPDATE
ON WICI_WHITELIST
REFERENCING NEW AS NEW 
FOR EACH ROW 
BEGIN
   :NEW.DATE_ADDED := SYSTIMESTAMP;
END;

--WHITELIST FOR DEVELOPMENT--
INSERT INTO WEBIC_OWNER.WICI_WHITELIST (AUTHFIELD_VALUE, AUTHORIZED) VALUES ('20:50:00:00:00:00', '1');
COMMIT;