# Ant

# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- doctor3

variables:
  antSDKDIR: $(SDKDIR)
  antKeyStore: $(RELEASEKEYSTOREDIRNAME)
  antKeyStoreAlias: $(WICI_KEYSTORE_ALIAS)
  antKeyStorePW: $(WICI_KEYSTORE_PW)
  antKeyStoreAliasPW: $(WICI_KEYSTOREALIAS_PW)
  antWEBAPP_ARTIFACT_DEBUG: $(Build.BinariesDirectory)\$(WEBAPPNAME)\$(WEBAPP_ARTIFACT_DEBUG)
  antWEBAPP_ARTIFACT_RELEASE: $(Build.BinariesDirectory)\$(WEBAPPNAME)\$(WEBAPP_ARTIFACT_RELEASE)
  antMOBILE_ARTIFACT_DEBUG: $(Build.BinariesDirectory)\$(MOBILEAPPNAME)\$(MOBILE_ARTIFACT_DEBUG)
  antMOBILE_ARTIFACT_RELEASE: $(Build.BinariesDirectory)\$(MOBILEAPPNAME)\$(MOBILE_ARTIFACT_RELEASE)
  antWEBAPP_BUILDXML: $(Build.Repository.LocalPath)\$(WEBAPPNAME)\build.xml
  antMOBILE_BUILDXML: $(Build.Repository.LocalPath)\$(MOBILEAPPNAME)\build.xml
jobs:

- job: BuildAPK

  pool: 
    name: WICI Agents
    demands: 
      - Agent.Name -equals WICIBuildVM

  steps: 
  - script: |
      echo 'Build.DefinitionName=$(Build.DefinitionName)'
      echo 'Build.BuildId=$(Build.BuildId)'
      echo 'Build.BuildNumber=$(Build.BuildNumber)'
      echo 'Pipeline.Workspace=$(Pipeline.Workspace)'
      echo 'Build.BinariesDirectory=$(Build.BinariesDirectory)'
      echo 'Build.SourcesDirectory=$(Build.SourcesDirectory)'
      echo 'Build.BinariesDirectory=$(Build.BinariesDirectory)'
      echo 'Agent.BuildDirectory=$(Agent.BuildDirectory)'
      echo 'antWEBAPP_BUILDXML=$(antWEBAPP_BUILDXML)'
      echo 'antMOBILE_BUILDXML=$(antMOBILE_BUILDXML)'
      echo 'antWEBAPP_ARTIFACT_DEBUG=$(antWEBAPP_ARTIFACT_DEBUG)'
      echo 'antWEBAPP_ARTIFACT_RELEASE=$(antWEBAPP_ARTIFACT_RELEASE)'
      echo 'SDKDIR=$(SDKDIR)'
      echo 'RELEASEKEYSTOREDIRNAME=$(RELEASEKEYSTOREDIRNAME)'
      echo 'antMOBILE_ARTIFACT_DEBUG=$(antMOBILE_ARTIFACT_DEBUG)'
      echo 'antMOBILE_ARTIFACT_RELEASE=$(antMOBILE_ARTIFACT_RELEASE)'
    displayName: 'Injected Vars'

  - script: set
    displayName: Show Agent Environment
    
  - script: dir
    workingDirectory: $(Agent.BuildDirectory)
    displayName: List contents of a folder

  - task: Ant@1
    displayName: Build WICIWebApp3
    inputs: 
      options: '-DwebAppArtifactDebugDir=$(antWEBAPP_ARTIFACT_DEBUG) -DwebAppArtifactReleaseDir=$(antWEBAPP_ARTIFACT_RELEASE)'
      workingDirectory: ''
      #buildFile: 'F:/DevTools/AzureAgent/vsts-agent-win-x64-3.232.3/_work/1/s/WICIWebApp3/build.xml'
      buildFile: $(antWEBAPP_BUILDXML)
      targets: 'build.all.no.tests.copy'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      #testResultsFiles: '**/TEST-*.xml'
      
  - task: Ant@1
    displayName: Build WICIMobile3
    inputs: 
      options: '-DsdkDir=$(antSDKDIR) -DreleaseKeystoreDir=$(antKeyStore) -DreleaseKeystoreAlias=$(antKeyStoreAlias) -DreleaseKeystorePassword=$(antKeyStorePW) -DreleaseKeystoreAliasPassword=$(antKeyStoreAliasPW) -DwebAppArtifactDebugDir=$(antWEBAPP_ARTIFACT_DEBUG) -DwebAppArtifactReleaseDir=$(antWEBAPP_ARTIFACT_RELEASE) -DmobileArtifactDebugDir=$(antMOBILE_ARTIFACT_DEBUG) -DmobileArtifactReleaseDir=$(antMOBILE_ARTIFACT_DEBUG) -DazureSourceDir=$(Build.ArtifactStagingDirectory)'
      workingDirectory: ''
      #buildFile: 'F:/DevTools/AzureAgent/vsts-agent-win-x64-3.232.3/_work/1/s/WICIMobile3/build.xml'
      buildFile: $(antMOBILE_BUILDXML)
      targets: 'jenkins.build.full.release.copy'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      
  # - task: PublishPipelineArtifact@1
  #   displayName: APK Publish
  #   inputs:
  #     targetPath: '$(antMOBILE_ARTIFACT)'
  #     artifact: 'WICIMobile3.apk'
  #     #publishLocation: 'pipeline'    
  - task: PublishBuildArtifacts@1
    inputs:
      #PathtoPublish: '$(Build.SourceDirectory)'
      ArtifactName: 'WICIMobile3'
      publishLocation: 'Container'