
package com.exacttarget.wsdl.partnerapi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * ExactTarget Partner API
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PartnerAPI", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", wsdlLocation = "WEB-INF/wsdl/etframework.wsdl")
public class PartnerAPI
    extends Service
{

    private final static URL PARTNERAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.exacttarget.wsdl.partnerapi.PartnerAPI.class.getName());

    static {
        URL url = null;
        try {
            url = com.exacttarget.wsdl.partnerapi.PartnerAPI.class.getResource("/WEB-INF/wsdl/etframework.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/etframework.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/etframework.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PARTNERAPI_WSDL_LOCATION = url;
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerAPI() {
        super(PARTNERAPI_WSDL_LOCATION, new QName("http://exacttarget.com/wsdl/partnerAPI", "PartnerAPI"));
    }

    /**
     * 
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap() {
        return super.getPort(new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap"), Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap"), Soap.class, features);
    }

}
