--
-- Main difference this file from the BRB_Tables.sql is instead of WEBIC_APP we have WEBIC_MAINT
--
--------------------------------------------------------------------------  START Persist WS tables  -------------------------------------------------------------------------- 

CREATE TABLE "WEBIC_OWNER"."CUSTOMERTRANSACTION"
  (
    "TRANSACTIONID" VARCHAR2(128 CHAR) NOT NULL,
    "PROFILEID"     VARCHAR2(128 CHAR) NOT NULL,
    "EMAIL"         VARCHAR2(60 CHAR) NOT NULL,
    "FIRSTNAME"     VARCHAR2(40 CHAR),
    "LASTNAME"      VARCHAR2(40 CHAR),
    "ADDRESSLINE1"  VARCHAR2(40 CHAR),
    "ADDRESSLINE2"  VARCHAR2(40 CHAR),
    "CITY"          VARCHAR2(24 CHAR),
    "PROVINCE"      VARCHAR2(3 CHAR),
    "POSTALCODE"    VARCHAR2(6 CHAR),
    "PHONENUMBER"   VARCHAR2(10 CHAR),
	"LOYALTYNUMBER" VARCHAR2(10 BYTE),
    "TRANSACTIONDATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,	
	"LOYALTYPROGRAM" VARCHAR2(128 CHAR),
	"REQUESTINGSYSTEM" VARCHAR2(128 CHAR) NOT NULL,
    CONSTRAINT "XPKWEBICECMSDID" PRIMARY KEY ("TRANSACTIONID")
  );
  COMMIT; 

 CREATE SEQUENCE webic_owner.ICSEQ_WEBIC_ECOM_SEED_ID 
 START WITH     1000 
 INCREMENT BY   1 
 NOCACHE 
 NOCYCLE; 
  
grant select, insert, update, delete on CUSTOMERTRANSACTION to WEBIC_MAINT; 
GRANT SELECT ON ICSEQ_WEBIC_ECOM_SEED_ID TO WEBIC_MAINT; 
COMMIT;  
  
  -- execute as WEBIC_MAINT user 
CREATE SYNONYM WEBIC_MAINT.CUSTOMERTRANSACTION FOR webic_owner.CUSTOMERTRANSACTION; 
CREATE SYNONYM WEBIC_MAINT.ICSEQ_WEBIC_ECOM_SEED_ID FOR webic_owner.ICSEQ_WEBIC_ECOM_SEED_ID; 
COMMIT; 

  
  CREATE TABLE "WEBIC_OWNER"."APPLICATIONTRANSACTION"
  (
    "TRANSACTIONID"     VARCHAR2(128 CHAR) NOT NULL,
    "SESSIONID"         VARCHAR2(128 CHAR) NOT NULL,
    "EXAMINTERACTIONID" VARCHAR2(128 CHAR) NOT NULL,
    "ACCOUNTAPPLICATIONDATA" CLOB,
	"TOKENIZATIONREFERENCENUMBER" VARCHAR2(128 CHAR),
	CONSTRAINT "APPLICATIONTRANSACTION_PK" PRIMARY KEY ("TRANSACTIONID"),
	CONSTRAINT "BRBTRANSACTION_FK" FOREIGN KEY ("TRANSACTIONID") REFERENCES "WEBIC_OWNER"."CUSTOMERTRANSACTION" ("TRANSACTIONID") ON DELETE CASCADE
  );
  COMMIT; 
  
grant select, insert, update, delete on APPLICATIONTRANSACTION to WEBIC_MAINT; 
GRANT SELECT ON ICSEQ_WEBIC_ECOM_SEED_ID TO WEBIC_MAINT; 
COMMIT; 

  -- execute as WEBIC_MAINT user 
CREATE SYNONYM WEBIC_MAINT.APPLICATIONTRANSACTION FOR WEBIC_OWNER.APPLICATIONTRANSACTION; 
COMMIT; 

--------------------------------------------------------------------------  END Persist WS tables  -------------------------------------------------------------------------- 

--------------------------------------------------------------------------  START Support Tracking Solution tables  -------------------------------------------------------------------------- 
 -- execute as webic_owner user 
CREATE TABLE "WEBIC_OWNER"."BRB_APP_STATE"
(
  "APPSTATEID" INTEGER NOT NULL,
  "APPSTATEDESC" VARCHAR2(128 BYTE) NOT NULL,
  CONSTRAINT "BRB_APP_STATE_PK" PRIMARY KEY ("APPSTATEID")  
);
COMMIT;

 -- execute as webic_owner user 
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('1', 'Application Completed - Approved');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('2', 'Application Completed - Pending');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('3', 'Application Completed - Declined');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('4', 'Abandon');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('5', 'Timeout');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('6', 'XSD Error');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('7', 'Account Application Error');
INSERT INTO "WEBIC_OWNER"."BRB_APP_STATE" (APPSTATEID, APPSTATEDESC) VALUES ('8', 'Middleware Timeout');
COMMIT;  

 -- execute as webic_owner user 
grant select, insert, update, delete on BRB_APP_STATE to WEBIC_MAINT; 
GRANT SELECT ON ICSEQ_WEBIC_ECOM_SEED_ID TO WEBIC_MAINT; 
COMMIT;  

  -- execute as WEBIC_MAINT user 
CREATE SYNONYM WEBIC_MAINT.BRB_APP_STATE FOR webic_owner.BRB_APP_STATE; 
  -- If not created yet
CREATE SYNONYM WEBIC_MAINT.ICSEQ_WEBIC_ECOM_SEED_ID FOR webic_owner.ICSEQ_WEBIC_ECOM_SEED_ID; 
COMMIT; 


CREATE TABLE "WEBIC_OWNER"."BRB_APP_SCREEN" 
  (
    "APPSCREENID" INTEGER NOT NULL, 
    "APPSCREENDESC" VARCHAR2(128 BYTE) NOT NULL,
     CONSTRAINT "BRB_APP_SCREEN_PK" PRIMARY KEY ("APPSCREENID")  
  );
COMMIT;  

 -- execute as webic_owner user 
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('0', 'No Screen, called from Ecomm');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('1', 'Overview Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('2', 'Nova Scotia Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('3', 'Personal Information Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('4', 'Optional Products Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('5', 'Confirmation Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('6', 'Edit Page-Tell Us About Yourself');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('7', 'Edit Page-Employment Information');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('8', 'Edit Page-Financial Information');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('9', 'Edit Page-Supplementary Card');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('10', 'Edit Page-Optional Insurance');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('11', 'Identity Verification Screen');
INSERT INTO "WEBIC_OWNER"."BRB_APP_SCREEN" (APPSCREENID, APPSCREENDESC) VALUES ('12', 'No Screen - Middleware Timeout');
COMMIT;  

-- execute as webic_owner user 
grant select, insert, update, delete on BRB_APP_SCREEN to WEBIC_MAINT; 
GRANT SELECT ON ICSEQ_WEBIC_ECOM_SEED_ID TO WEBIC_MAINT; 
COMMIT;  

-- execute as WEBIC_MAINT user 
CREATE SYNONYM WEBIC_MAINT.BRB_APP_SCREEN FOR webic_owner.BRB_APP_SCREEN; 


CREATE TABLE "WEBIC_OWNER"."BRB_STATE_TRACKER" 
  (
    "APPID" VARCHAR2(128 CHAR) NOT NULL, 
    "APPSTATEID" INTEGER,
    "ABANDONSCREENID" INTEGER,
    "STARTDATETIME" TIMESTAMP (6),
    "ENDDATETIME" TIMESTAMP (6),
    CONSTRAINT "BRB_STATE_TRACKER_PK" PRIMARY KEY ("APPID"),  
    CONSTRAINT "APPSTATEID_FK" FOREIGN KEY ("APPSTATEID") REFERENCES "WEBIC_OWNER"."BRB_APP_STATE" ("APPSTATEID"),
    CONSTRAINT "ABANDONSCREENID_FK" FOREIGN KEY ("ABANDONSCREENID") REFERENCES "WEBIC_OWNER"."BRB_APP_SCREEN" ("APPSCREENID")
  );
COMMIT;

-- execute as webic_owner user 
grant select, insert, update, delete on BRB_STATE_TRACKER to WEBIC_MAINT; 
GRANT SELECT ON ICSEQ_WEBIC_ECOM_SEED_ID TO WEBIC_MAINT; 
COMMIT;  

-- execute as WEBIC_MAINT user 
CREATE SYNONYM WEBIC_MAINT.BRB_STATE_TRACKER FOR webic_owner.BRB_STATE_TRACKER; 

--------------------------------------------------------------------------  END Support Tracking Solution tables  -------------------------------------------------------------------------- 
