
package com.channel.ctfs.ctc.webicgateway;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "messageFault", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/")
public class ProcessRequestFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MessageFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ProcessRequestFaultMsg(String message, MessageFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ProcessRequestFaultMsg(String message, MessageFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.channel.ctfs.ctc.webicgateway.MessageFault
     */
    public MessageFault getFaultInfo() {
        return faultInfo;
    }

}
