
package com.channel.ctfs.ctc.webicgateway;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebICGateway", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/", wsdlLocation = "WEB-INF/wsdl/WebICGateway.wsdl")
public class WebICGateway_Service
    extends Service
{

    private final static URL WEBICGATEWAY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.channel.ctfs.ctc.webicgateway.WebICGateway_Service.class.getName());

    static {
        URL url = null;
        try {
            url = com.channel.ctfs.ctc.webicgateway.WebICGateway_Service.class.getResource("/WEB-INF/wsdl/WebICGateway.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/WebICGateway.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/WebICGateway.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBICGATEWAY_WSDL_LOCATION = url;
    }

    public WebICGateway_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebICGateway_Service() {
        super(WEBICGATEWAY_WSDL_LOCATION, new QName("http://www.ctc.ctfs.channel.com/WebICGateway/", "WebICGateway"));
    }

    /**
     * 
     * @return
     *     returns WebICGateway
     */
    @WebEndpoint(name = "AccountAcquisitionPortal")
    public WebICGateway getAccountAcquisitionPortal() {
        return super.getPort(new QName("http://www.ctc.ctfs.channel.com/WebICGateway/", "AccountAcquisitionPortal"), WebICGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebICGateway
     */
    @WebEndpoint(name = "AccountAcquisitionPortal")
    public WebICGateway getAccountAcquisitionPortal(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ctc.ctfs.channel.com/WebICGateway/", "AccountAcquisitionPortal"), WebICGateway.class, features);
    }

}
