
package com.ctfs.BRB.persistservice;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersistServiceDelegate", targetNamespace = "http://persistservice.BRB.ctfs.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
@HandlerChain(file = "handler-config.xml")
public interface PersistServiceDelegate {


    /**
     * 
     * @param saveBrbRequest
     * @return
     *     returns com.ctfs.BRB.persistservice.BrbResponseType
     */
    @WebMethod(operationName = "SaveCustomerBrbData", action = "http://persistservice.BRB.ctfs.com/")
    @WebResult(name = "response", targetNamespace = "http://persistservice.BRB.ctfs.com/", partName = "SaveBrbResponse")
    public BrbResponseType saveCustomerBrbData(
        @WebParam(name = "request", targetNamespace = "http://persistservice.BRB.ctfs.com/", partName = "SaveBrbRequest")
        BrbRequestType saveBrbRequest);

}
