CREATE TABLE WEBIC_OWNER.WICI_REQUESTQUEUE 
(
	"TRANSACTION_ID" VARCHAR2(128 BYTE) NOT NULL, 
	"TRANSACTION_TYPE" VARCHAR2(25 BYTE), 
	"TRANSACTION_STATE" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(128 BYTE), 
	"PROCESS_DATE" TIMESTAMP(6), 
	"RESPONSE_DATA" CLOB,
	"REQUEST_DATA" CLOB 
)
COMMIT;

GRANT SELECT, INSERT, UPDATE, DELETE on WEBIC_OWNER.WICI_REQUESTQUEUE to WEBIC_APP;
COMMIT;

-- execute as webic_app user 
CREATE SYNONYM WEBIC_APP.WICI_REQUESTQUEUE FOR WEBIC_OWNER.WICI_REQUESTQUEUE;
COMMIT; 