//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ctc.ctfs.channel.sharedservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="passFail">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="P"/>
 *               &lt;enumeration value="F"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="resultMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseArgument1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseArgument2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceResponse", namespace = "http://web.sharedservices.ctfs.com/SharedWebServices/", propOrder = {
    "passFail",
    "resultMessage",
    "responseArgument1",
    "responseArgument2"
})
public class ServiceResponse {

    @XmlElement(required = true)
    protected String passFail;
    protected String resultMessage;
    protected String responseArgument1;
    protected String responseArgument2;

    /**
     * Gets the value of the passFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassFail() {
        return passFail;
    }

    /**
     * Sets the value of the passFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassFail(String value) {
        this.passFail = value;
    }

    /**
     * Gets the value of the resultMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultMessage() {
        return resultMessage;
    }

    /**
     * Sets the value of the resultMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultMessage(String value) {
        this.resultMessage = value;
    }

    /**
     * Gets the value of the responseArgument1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseArgument1() {
        return responseArgument1;
    }

    /**
     * Sets the value of the responseArgument1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseArgument1(String value) {
        this.responseArgument1 = value;
    }

    /**
     * Gets the value of the responseArgument2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseArgument2() {
        return responseArgument2;
    }

    /**
     * Sets the value of the responseArgument2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseArgument2(String value) {
        this.responseArgument2 = value;
    }

}
