//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ctc.ctfs.channel.sharedservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operatorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceArgument1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceArgument2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceArgument3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceArgument4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRequest", namespace = "http://web.sharedservices.ctfs.com/SharedWebServices/", propOrder = {
    "operatorId",
    "serviceName",
    "methodName",
    "serviceArgument1",
    "serviceArgument2",
    "serviceArgument3",
    "serviceArgument4"
})
public class ServiceRequest {

    @XmlElement(required = true)
    protected String operatorId;
    @XmlElement(required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected String methodName;
    protected String serviceArgument1;
    protected String serviceArgument2;
    protected String serviceArgument3;
    protected String serviceArgument4;

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorId(String value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the methodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the value of the methodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

    /**
     * Gets the value of the serviceArgument1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceArgument1() {
        return serviceArgument1;
    }

    /**
     * Sets the value of the serviceArgument1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceArgument1(String value) {
        this.serviceArgument1 = value;
    }

    /**
     * Gets the value of the serviceArgument2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceArgument2() {
        return serviceArgument2;
    }

    /**
     * Sets the value of the serviceArgument2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceArgument2(String value) {
        this.serviceArgument2 = value;
    }

    /**
     * Gets the value of the serviceArgument3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceArgument3() {
        return serviceArgument3;
    }

    /**
     * Sets the value of the serviceArgument3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceArgument3(String value) {
        this.serviceArgument3 = value;
    }

    /**
     * Gets the value of the serviceArgument4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceArgument4() {
        return serviceArgument4;
    }

    /**
     * Sets the value of the serviceArgument4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceArgument4(String value) {
        this.serviceArgument4 = value;
    }

}
