
package com.cantire.persistservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersistServiceDelegate", targetNamespace = "http://persistservice.cantire.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersistServiceDelegate {


    /**
     * 
     * @param saveCardRequest
     * @return
     *     returns com.cantire.persistservice.CardResponseType
     */
    @WebMethod(operationName = "SaveCustomerCardData", action = "http://persistservice.cantire.com/")
    @WebResult(name = "response", targetNamespace = "http://persistservice.cantire.com/", partName = "SaveCardResponse")
    public CardResponseType saveCustomerCardData(
        @WebParam(name = "request", targetNamespace = "http://persistservice.cantire.com/", partName = "SaveCardRequest")
        CardRequestType saveCardRequest);

}
