
package com.exacttarget.wsdl.partnerapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Soap", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.exacttarget.partner.fault.ObjectFactory.class,
    com.exacttarget.wsdl.partnerapi.ObjectFactory.class
})
public interface Soap {


    /**
     * Create objects
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.CreateResponse
     */
    @WebMethod(operationName = "Create", action = "Create")
    @WebResult(name = "CreateResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public CreateResponse create(
        @WebParam(name = "CreateRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        CreateRequest parameters);

    /**
     * Retrieve objects
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.RetrieveResponseMsg
     */
    @WebMethod(operationName = "Retrieve", action = "Retrieve")
    @WebResult(name = "RetrieveResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public RetrieveResponseMsg retrieve(
        @WebParam(name = "RetrieveRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        RetrieveRequestMsg parameters);

    /**
     * Update objects
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.UpdateResponse
     */
    @WebMethod(operationName = "Update", action = "Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "UpdateRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        UpdateRequest parameters);

    /**
     * Delete objects
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.DeleteResponse
     */
    @WebMethod(operationName = "Delete", action = "Delete")
    @WebResult(name = "DeleteResponse", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public DeleteResponse delete(
        @WebParam(name = "DeleteRequest", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        DeleteRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.QueryResponseMsg
     */
    @WebMethod(operationName = "Query", action = "Query")
    @WebResult(name = "QueryResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public QueryResponseMsg query(
        @WebParam(name = "QueryRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        QueryRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.DefinitionResponseMsg
     */
    @WebMethod(operationName = "Describe", action = "Describe")
    @WebResult(name = "DefinitionResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public DefinitionResponseMsg describe(
        @WebParam(name = "DefinitionRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        DefinitionRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.ExecuteResponseMsg
     */
    @WebMethod(operationName = "Execute", action = "Execute")
    @WebResult(name = "ExecuteResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public ExecuteResponseMsg execute(
        @WebParam(name = "ExecuteRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        ExecuteRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.PerformResponseMsg
     */
    @WebMethod(operationName = "Perform", action = "Perform")
    @WebResult(name = "PerformResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public PerformResponseMsg perform(
        @WebParam(name = "PerformRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        PerformRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.ConfigureResponseMsg
     */
    @WebMethod(operationName = "Configure", action = "Configure")
    @WebResult(name = "ConfigureResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public ConfigureResponseMsg configure(
        @WebParam(name = "ConfigureRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        ConfigureRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.ScheduleResponseMsg
     */
    @WebMethod(operationName = "Schedule", action = "Schedule")
    @WebResult(name = "ScheduleResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public ScheduleResponseMsg schedule(
        @WebParam(name = "ScheduleRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        ScheduleRequestMsg parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.VersionInfoResponseMsg
     */
    @WebMethod(operationName = "VersionInfo", action = "VersionInfo")
    @WebResult(name = "VersionInfoResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public VersionInfoResponseMsg versionInfo(
        @WebParam(name = "VersionInfoRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        VersionInfoRequestMsg parameters);

    /**
     * Perform ad hoc data extracts
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.ExtractResponseMsg
     */
    @WebMethod(operationName = "Extract", action = "Extract")
    @WebResult(name = "ExtractResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public ExtractResponseMsg extract(
        @WebParam(name = "ExtractRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        ExtractRequestMsg parameters);

    /**
     * Get Current System Status
     * 
     * @param parameters
     * @return
     *     returns com.exacttarget.wsdl.partnerapi.SystemStatusResponseMsg
     */
    @WebMethod(operationName = "GetSystemStatus", action = "GetSystemStatus")
    @WebResult(name = "SystemStatusResponseMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
    public SystemStatusResponseMsg getSystemStatus(
        @WebParam(name = "SystemStatusRequestMsg", targetNamespace = "http://exacttarget.com/wsdl/partnerAPI", partName = "parameters")
        SystemStatusRequestMsg parameters);

}
