
package com.ctfs.esockettransact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ctfs.esockettransactio.ESocketTransactInput;
import com.ctfs.esockettransactio.ESocketTransactOutput;
import com.ctfs.esockettransactio.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "esocketTransact", targetNamespace = "http://ctfs.com/esocketTransact/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EsocketTransact {


    /**
     * 
     * @param request
     * @return
     *     returns com.ctfs.esockettransactio.ESocketTransactOutput
     * @throws PGCError
     */
    @WebMethod(action = "http://ctfs.com/esocketTransact/transact")
    @WebResult(name = "transactResponse", targetNamespace = "http://ctfs.com/esocketTransactIo/", partName = "response")
    public ESocketTransactOutput transact(
        @WebParam(name = "transactRequest", targetNamespace = "http://ctfs.com/esocketTransactIo/", partName = "request")
        ESocketTransactInput request)
        throws PGCError
    ;

}
