
package com.channel.ctfs.ctc.webicgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebICGateway", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebICGateway {


    /**
     * 
     * @param requestDocument
     * @param messageHeader
     * @return
     *     returns com.channel.ctfs.ctc.webicgateway.ResponseBody
     * @throws ProcessRequestFaultMsg
     */
    @WebMethod(operationName = "ProcessRequest", action = "http://www.ctc.ctfs.com/WebICGateway/ProcessRequest")
    @WebResult(name = "ResponseBody", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/", partName = "responseBody")
    public ResponseBody processRequest(
        @WebParam(name = "MessageHeader", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/", header = true, mode = WebParam.Mode.INOUT, partName = "messageHeader")
        Holder<MessageHeader> messageHeader,
        @WebParam(name = "RequestBody", targetNamespace = "http://www.ctc.ctfs.channel.com/WebICGateway/", partName = "requestDocument")
        RequestBody requestDocument)
        throws ProcessRequestFaultMsg
    ;

}
