//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ctc.ctfs.channel.webicaddressverification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ctc.ctfs.channel.webicaddressverification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ctc.ctfs.channel.webicaddressverification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebICAddressLookupRequest }
     * 
     */
    public WebICAddressLookupRequest createWebICAddressLookupRequest() {
        return new WebICAddressLookupRequest();
    }

    /**
     * Create an instance of {@link WebICAddressLookupResponse }
     * 
     */
    public WebICAddressLookupResponse createWebICAddressLookupResponse() {
        return new WebICAddressLookupResponse();
    }

}
