
package com.ctc.ctfs.eCommUpdateCardData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IResponseService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IResponseService {


    /**
     * 
     * @param rst
     * @return
     *     returns com.ctc.ctfs.eCommUpdateCardData.CardResponseType
     */
    @WebMethod(operationName = "SaveCustomerCardData", action = "http://tempuri.org/IResponseService/SaveCustomerCardData")
    @WebResult(name = "SaveCustomerCardDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveCustomerCardData", targetNamespace = "http://tempuri.org/", className = "com.ctc.ctfs.eCommUpdateCardData.SaveCustomerCardData")
    @ResponseWrapper(localName = "SaveCustomerCardDataResponse", targetNamespace = "http://tempuri.org/", className = "com.ctc.ctfs.eCommUpdateCardData.SaveCustomerCardDataResponse")
    public CardResponseType saveCustomerCardData(
        @WebParam(name = "rst", targetNamespace = "http://tempuri.org/")
        CardRequestType rst);

}
