
package com.ctc.ctfs.eCommUpdateCardData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ResponseService", targetNamespace = "http://tempuri.org/", wsdlLocation = "WEB-INF/wsdl/ECommUpdatePersistService.wsdl")
public class ResponseService
    extends Service
{

    private final static URL RESPONSESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ctc.ctfs.eCommUpdateCardData.ResponseService.class.getName());

    static {
        URL url = null;
        try {
            url = com.ctc.ctfs.eCommUpdateCardData.ResponseService.class.getResource("/WEB-INF/wsdl/ECommUpdatePersistService.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/ECommUpdatePersistService.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/ECommUpdatePersistService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RESPONSESERVICE_WSDL_LOCATION = url;
    }

    public ResponseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponseService() {
        super(RESPONSESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "ResponseService"));
    }

    /**
     * 
     * @return
     *     returns IResponseService
     */
    @WebEndpoint(name = "BasicHttpBinding_IResponseService")
    public IResponseService getBasicHttpBindingIResponseService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IResponseService"), IResponseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IResponseService
     */
    @WebEndpoint(name = "BasicHttpBinding_IResponseService")
    public IResponseService getBasicHttpBindingIResponseService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IResponseService"), IResponseService.class, features);
    }

}
